##Config for Mailslurper
:from: 'amigo_oculto@example.com'
:subject: 'Veja quem voce tirou no amigo oculto'
:via: :smtp
:via_options:
  :address: 'localhost'
  :port: '2500'
#Config for Gmail
#:from: 'amigo_oculto@example.com'
#:subject: 'Veja quem voce tirou no amigo oculto'
#:via: :smtp
#:via_options:
#  :user_name: user
#  :password: password
#  :address: 'smtp.gmail.com'
#  :port: 587
#  :enable_starttls_auto: true
#  :authentication: :plain
#  :domain: 'localhost.localdomain'
